sudo: required
services:
  - docker

before_install:
  - docker build -t votoznotna/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true votoznotna/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-489172308893"
  backet_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
